name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo build --release --verbose
          
    - uses: actions/upload-artifact@v3
      with:
        name: boat3d
        path: target/release/boat3d.exe
